import os
import subprocess
import requests
import uuid
import sys
from functools import partial

# Redirect prints to stderr
print = partial(print, file=sys.stderr)

from config import GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO, GITHUB_BASE_BRANCH, SOURCE_DIR

def apply_fix_and_raise_pr(fix, original_file_path, original_content):
    if fix['originalCode'] not in original_content:
        raise ValueError("Original code block from AI not found in the target file.")
        
    new_content = original_content.replace(fix['originalCode'], fix['fixedCode'])
    
    with open(original_file_path, 'w', encoding='utf-8') as f:
        f.write(new_content)
        
    branch_name = f"auto-fix-{uuid.uuid4().hex[:8]}"
    
    def run_git(cmd):
        subprocess.run(cmd, cwd=SOURCE_DIR, check=True, shell=True, stdout=sys.stderr, stderr=sys.stderr)
        
    print(f"  [Git] Creating branch {branch_name}...")
    run_git(f"git checkout -b {branch_name}")
    run_git(f"git add {os.path.relpath(original_file_path, SOURCE_DIR)}")
    
    commit_msg = fix['prTitle'].replace('"', '\\"')
    run_git(f'git commit -m "{commit_msg}"')
    run_git(f"git push -u origin {branch_name}")
    
    print("  [GitHub] Opening Pull Request...")
    url = f"https://api.github.com/repos/{GITHUB_OWNER}/{GITHUB_REPO}/pulls"
    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "X-GitHub-Api-Version": "2022-11-28"
    }
    data = {
        "title": fix['prTitle'],
        "body": f"{fix['prBody']}\n\n*Automated fix generated by Groq*",
        "head": branch_name,
        "base": GITHUB_BASE_BRANCH
    }
    
    response = requests.post(url, headers=headers, json=data)
    response.raise_for_status()
    
    pr_url = response.json().get('html_url')
    
    # Checkout back to base branch
    run_git(f"git checkout {GITHUB_BASE_BRANCH}")
    
    return {"branchName": branch_name, "prUrl": pr_url}
